apiVersion: v1
annotations:
  # --- Provenance Metadata ---
  repackage.provenance/repackaged-by: "mirrorctl dev"
  repackage.provenance/original-chart-url: "https://helm.influxdata.com"
  repackage.provenance/original-chart-name: "influxdb"
  repackage.provenance/original-chart-version: "4.12.5"
  repackage.provenance/timestamp: "2025-11-14T16:38:32Z"
appVersion: 1.8.10
description: Scalable datastore for metrics, events, and real-time analytics.
home: https://www.influxdata.com/time-series-platform/influxdb/
keywords:
- influxdb
- database
- timeseries
- influxdata
maintainers:
- email: rawkode@influxdata.com
  name: rawkode
- email: giacomo@influxdata.com
  name: gitirabassi
- email: urakiny@gmail.com
  name: aisuko
- email: naseem@transit.app
  name: naseemkullah
name: influxdb
sources:
- https://github.com/influxdata/influxdb
version: 4.12.5-poc
