apiVersion: v2
annotations:
  # --- Provenance Metadata ---
  repackage.provenance/repackaged-by: "mirrorctl dev"
  repackage.provenance/original-chart-url: "https://grafana.github.io/helm-charts"
  repackage.provenance/original-chart-name: "promtail"
  repackage.provenance/original-chart-version: "6.15.5"
  repackage.provenance/timestamp: "2025-11-14T16:23:46Z"
appVersion: 2.9.3
description: Promtail is an agent which ships the contents of local logs to a Loki
  instance
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
maintainers:
- email: lokiproject@googlegroups.com
  name: Loki Maintainers
- name: unguiculus
name: promtail
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
type: application
version: 6.15.5-poc
